type: table
columns:
  - name: gene
    type: string
    description: Gene name (row names)
  - name: sample_*
    type: number
    description: Expression value for each sample (one column per sample)
required:
  - gene
pattern:
  header: true
  delimiter: '\t'
  row_names: gene
  col_names: true
