run_name: "test1"
#run_number: 1

genie3_params:
  scrnaseq_input: "resources/GSE158067/GSE158067_gene_exp_mtx_mutant.txt"
  n_trees: 1  # set this way for testing purposes, should be set to ~50 for real runs

perturb_params:
  perturbations: "resources/GSE158067/GSE158067_mutations_by_sample.txt"
  pathogenicity_score_transform: "threshold"
  k: 10.0
  t: 0.5
